<?php

namespace SameOldNick\BackupManager\Concerns;

use SameOldNick\BackupManager\Broadcasting\Access\ChannelAccessManager;

trait GeneratesChannelId
{
    /**
     * Creates a unique channel ID based on the given UUID.
     *
     * @param  string  $uuid  The UUID to include in the channel ID
     * @return string A unique channel ID for the backup process (e.g. "backups.{uuid}")
     */
    public function createChannelId(string $uuid): string
    {
        return app(ChannelAccessManager::class)->createChannelId($this->getChannelIdPrefix(), $uuid);
    }

    /**
     * Retrieves the prefix to use for channel IDs generated by this class.
     *
     * @return string The prefix to use for channel IDs (e.g. "backups")
     */
    abstract protected function getChannelIdPrefix(): string;
}
