<?php

namespace SameOldNick\BackupManager\Tests\Unit;

use Illuminate\Filesystem\FilesystemAdapter;
use League\Flysystem\Ftp\FtpAdapter;
use League\Flysystem\Local\LocalFilesystemAdapter;
use League\Flysystem\PhpseclibV3\SftpAdapter;
use PHPUnit\Framework\Attributes\Test;
use SameOldNick\BackupManager\Filesystem\DynamicFilesystemManager;
use SameOldNick\BackupManager\Models\FilesystemConfiguration;
use SameOldNick\BackupManager\Models\FilesystemConfigurationFTP;
use SameOldNick\BackupManager\Models\FilesystemConfigurationLocal;
use SameOldNick\BackupManager\Models\FilesystemConfigurationSFTP;
use SameOldNick\BackupManager\Tests\TestCase;

class DynamicFilesystemManagerTest extends TestCase
{
    /**
     * The resolved driver name must match the name from the filesystem config,
     * generated by FilesystemConfiguration::getFilesystemConfig().
     */
    #[Test]
    public function it_resolves_dynamic_local_disk_when_active_configuration_exists(): void
    {
        $fsConfig = FilesystemConfiguration::factory()->local()->create([
            'is_active' => true,
        ]);

        $diskName = "dynamic-{$fsConfig->slug}";

        /** @var FilesystemAdapter $disk */
        $disk = $this->app->make('filesystem')->disk($diskName);

        $this->assertInstanceOf(FilesystemAdapter::class, $disk);
        $this->assertInstanceOf(LocalFilesystemAdapter::class, $disk->getAdapter());
    }

    #[Test]
    public function it_resolves_dynamic_sftp_disk_when_active_configuration_exists(): void
    {
        $fsConfig = FilesystemConfiguration::factory()->sftp('password')->create([
            'is_active' => true,
        ]);

        $diskName = "dynamic-{$fsConfig->slug}";

        /** @var FilesystemAdapter $disk */
        $disk = $this->app->make('filesystem')->disk($diskName);

        $this->assertInstanceOf(FilesystemAdapter::class, $disk);
        $this->assertInstanceOf(SftpAdapter::class, $disk->getAdapter());
    }

    #[Test]
    public function it_resolves_dynamic_ftp_disk_when_active_configuration_exists(): void
    {
        $fsConfig = FilesystemConfiguration::factory()->ftp()->create([
            'is_active' => true,
        ]);

        $diskName = "dynamic-{$fsConfig->slug}";

        /** @var FilesystemAdapter $disk */
        $disk = $this->app->make('filesystem')->disk($diskName);

        $this->assertInstanceOf(FilesystemAdapter::class, $disk);
        $this->assertInstanceOf(FtpAdapter::class, $disk->getAdapter());
    }

    #[Test]
    public function it_throws_exception_when_no_configuration_matches_dynamic_disk(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage("Disk [dynamic-nonexistent-slug] does not have a configured driver.");

        $this->app->make('filesystem')->disk('dynamic-nonexistent-slug');
    }

    #[Test]
    public function it_throws_exception_when_matching_configuration_is_inactive(): void
    {
        $fsConfig = FilesystemConfiguration::factory()->local()->create([
            'is_active' => false,
        ]);

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage("Disk [dynamic-{$fsConfig->slug}] does not have a configured driver.");

        $this->app->make('filesystem')->disk("dynamic-{$fsConfig->slug}");
    }

    #[Test]
    public function it_falls_through_to_parent_for_non_dynamic_disk_names(): void
    {
        // A standard Laravel disk (not prefixed with 'dynamic-') should
        // resolve through the parent FilesystemManager without interference.
        $disk = $this->app->make('filesystem')->disk('local');

        $this->assertInstanceOf(FilesystemAdapter::class, $disk);
    }

    #[Test]
    public function get_dynamic_filesystem_configuration_returns_model_when_active_match_exists(): void
    {
        $fsConfig = FilesystemConfiguration::factory()->local()->create([
            'is_active' => true,
        ]);

        $manager = $this->app->make('filesystem');

        $this->assertInstanceOf(DynamicFilesystemManager::class, $manager);

        $result = $this->invokeProtectedMethod($manager, 'getDynamicFilesystemConfiguration', [
            "dynamic-{$fsConfig->slug}",
        ]);

        $this->assertInstanceOf(FilesystemConfiguration::class, $result);
        $this->assertTrue($result->is($fsConfig));
    }

    #[Test]
    public function get_dynamic_filesystem_configuration_returns_null_when_no_match_exists(): void
    {
        $manager = $this->app->make('filesystem');

        $this->assertInstanceOf(DynamicFilesystemManager::class, $manager);

        $result = $this->invokeProtectedMethod($manager, 'getDynamicFilesystemConfiguration', [
            'dynamic-nonexistent-slug',
        ]);

        $this->assertNull($result);
    }

    #[Test]
    public function get_dynamic_filesystem_configuration_returns_null_when_match_is_inactive(): void
    {
        $fsConfig = FilesystemConfiguration::factory()->local()->create([
            'is_active' => false,
        ]);

        $manager = $this->app->make('filesystem');

        $this->assertInstanceOf(DynamicFilesystemManager::class, $manager);

        $result = $this->invokeProtectedMethod($manager, 'getDynamicFilesystemConfiguration', [
            "dynamic-{$fsConfig->slug}",
        ]);

        $this->assertNull($result);
    }

    #[Test]
    public function get_driver_config_delegates_to_filesystem_configuration_contract(): void
    {
        $localConfig = FilesystemConfigurationLocal::create([
            'root' => 'test-backups',
            'extra' => null,
        ]);

        $fsConfig = FilesystemConfiguration::factory()->create([
            'name' => 'Test Config',
            'slug' => 'test-config',
            'disk_type' => 'local',
            'is_active' => true,
            'configurable_type' => $localConfig->getMorphClass(),
            'configurable_id' => $localConfig->id,
        ]);

        $manager = $this->app->make('filesystem');
        $this->assertInstanceOf(DynamicFilesystemManager::class, $manager);

        $config = $this->invokeProtectedMethod($manager, 'getDriverConfig', [$fsConfig]);

        $this->assertIsArray($config);
        $this->assertArrayHasKey('name', $config);
        $this->assertArrayHasKey('driver', $config);
        $this->assertArrayHasKey('root', $config);
        $this->assertEquals('test-config', $config['name']);
        $this->assertEquals('local', $config['driver']);
    }

    #[Test]
    public function resolved_disk_config_matches_persisted_filesystem_configuration(): void
    {
        $sftpConfig = FilesystemConfigurationSFTP::factory()->authKey()->create();

        $fsConfig = FilesystemConfiguration::factory()->create([
            'name' => 'Production SFTP',
            'slug' => 'production-sftp',
            'disk_type' => 'sftp',
            'is_active' => true,
            'configurable_type' => $sftpConfig->getMorphClass(),
            'configurable_id' => $sftpConfig->id,
        ]);

        /** @var FilesystemAdapter $disk */
        $disk = $this->app->make('filesystem')->disk('dynamic-production-sftp');

        $config = $disk->getConfig();

        $this->assertEquals('sftp', $config['driver']);
        $this->assertEquals($sftpConfig->host, $config['host']);
        $this->assertEquals($sftpConfig->port, $config['port']);
        $this->assertEquals($sftpConfig->username, $config['username']);
        $this->assertEquals($sftpConfig->private_key, $config['privateKey']);
        $this->assertEquals($sftpConfig->passphrase, $config['passphrase']);
    }

    #[Test]
    public function resolved_disk_uses_slug_from_configuration_not_name(): void
    {
        // The disk is looked up by slug, so the name can differ from the slug.
        $fsConfig = FilesystemConfiguration::factory()->local()->create([
            'name' => 'My Custom Backup Disk',
            'slug' => 'custom-slug',
            'is_active' => true,
        ]);

        // Lookup by slug works
        $disk = $this->app->make('filesystem')->disk('dynamic-custom-slug');
        $this->assertInstanceOf(FilesystemAdapter::class, $disk);

        // Lookup by name does NOT work (name is 'my-custom-backup-disk' when
        // slugified by getFilesystemConfig, but the manager only matches slug)
        $this->expectException(\InvalidArgumentException::class);
        $this->app->make('filesystem')->disk('dynamic-my-custom-backup-disk');
    }

    /**
     * Invoke a protected/private method on an object using reflection.
     *
     * @param  object  $object
     * @param  string  $method
     * @param  array<int, mixed>  $args
     * @return mixed
     */
    private function invokeProtectedMethod(object $object, string $method, array $args = []): mixed
    {
        $reflection = new \ReflectionMethod($object, $method);

        return $reflection->invoke($object, ...$args);
    }
}
